### ISSUE TITLE
SQL6031N  Error in the db2nodes.cfg file at line number "1".  Reason code "10".

### ISSUE THREAD

**Issue by jencii** [angoca/db2-docker#20]
after db2profile; db2start

**Comment by asgerjensen** [comment]
This is because the hostname of the docker image is set to the sha of the image, while the container starts with another name.

Put something like  this in your Dockerfile, after changing user to db2inst1

RUN echo "0 localhost 0" > sqllib/db2nodes.cfg

**Comment by angoca** [comment]
Done, the creation of the instance includes this change in the db2nodes file (only for ESE, no EXPC)
